it_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
]

task_manager/urls.py
from django.urls import path

from task_manager.views import (
    index,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    toggle_assign_to_task,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list"
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/toggle-assign/",
        toggle_assign_to_task,
        name="toggle-task-assign",
    ),
]

app_name = "task_manager"

task_manager/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Position(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        to=Position,
        on_delete=models.CASCADE,
        related_name="workers",
        null=True,
        blank=True
    )

    class Meta:
        ordering = ["id"]
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self) -> str:
        return f"{self.username} : {self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("task_manager:worker-detail", kwargs={"pk": self.pk})


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    priority_choises = [
        ("UR", "Urgent"),
        ("HG", "High"),
        ("MD", "Medium"),
        ("LW", "Low"),
    ]
    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=2, choices=priority_choises)
    task_type = models.ForeignKey(
        to=TaskType, on_delete=models.CASCADE, related_name="tasks"
    )
    assignees = models.ManyToManyField(
        to=get_user_model(),
        related_name="tasks"
    )

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return self.name

task_manager/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from task_manager.models import Worker, Task


class PositionSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class TaskTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name", "last_name", "position"
        )


class TaskCreateForm(forms.ModelForm):
    deadline = forms.DateField(
        label="deadline",
        required=True,
        widget=forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"}),
        input_formats=["%Y-%m-%d"]
    )

    class Meta:
        model = Task
        fields = "__all__"

task_manager/views.py
from typing import Dict

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from task_manager.forms import (
    PositionSearchForm,
    TaskTypeSearchForm,
    WorkerSearchForm,
    WorkerCreationForm,
    TaskSearchForm, TaskCreateForm,
)
from task_manager.models import Position, Worker, TaskType, Task


def index(request: HttpRequest) -> HttpResponse:

    completed_task = Task.objects.filter(is_completed=True).count()
    unfinished_task = Task.objects.filter(is_completed=False).count()
    num_workers = Worker.objects.filter(
        tasks__is_completed=False
    ).distinct().count()

    context = {
        "completed_task": completed_task,
        "unfinished_task": unfinished_task,
        "num_workers": num_workers,
    }
    return render(
        request=request,
        template_name="task_manager/index.html",
        context=context
    )


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs) -> Dict:
        context = super(PositionListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = PositionSearchForm(initial={"name": name})
        return context

    def get_queryset(self) -> QuerySet:
        queryset = Position.objects.all()
        form = PositionSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("task_manager:position-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> Dict:
        context = super(
            WorkerListView, self
        ).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self) -> QuerySet:
        queryset = Worker.objects.all()
        form = WorkerSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.prefetch_related("tasks__task_type")


class WorkerCreateView(generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("task_manager:worker-list")


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    context_object_name = "task_type_list"
    template_name = "task_manager/task_type_list.html"
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs) -> Dict:
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskTypeSearchForm(initial={"name": name})
        return context

    def get_queryset(self) -> QuerySet:
        queryset = TaskType.objects.all()
        form = TaskTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    template_name = "task_manager/task_type_form.html"
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-type-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    template_name = "task_manager/task_type_form.html"
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-type-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    template_name = "task_manager/task_type_confirm_delete.html"
    success_url = reverse_lazy("task_manager:task-type-list")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task

    def get_context_data(self, *, object_list=None, **kwargs) -> Dict:
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskSearchForm(initial={"name": name})
        return context

    def get_queryset(self) -> QuerySet:
        queryset = Task.objects.all()
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskCreateForm
    success_url = reverse_lazy("task_manager:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")


@login_required
def toggle_assign_to_task(request, pk):
    worker = Worker.objects.get(id=request.user.id)
    if (
        Task.objects.get(id=pk) in worker.tasks.all()
    ):
        worker.tasks.remove(pk)
    else:
        worker.tasks.add(pk)
    return HttpResponseRedirect(reverse_lazy(
        "task_manager:task-detail", args=[pk])
    )

templates/task_manager/index.html
{% extends "base.html" %}

{% block content %}
  <h1><b>Welcome to IT Task Manager!</b></h1>
    <p>
    This task manager is a web-based application designed to help users organize
      and keep track of their tasks efficiently. Users can add, edit,
      and mark tasks as completed. The user interface is clean and user-friendly,
      providing a seamless experience for managing daily tasks.
    </p>
    <ul>
        <li><strong>Currently completed tasks:</strong> {{ completed_task }}</li>
        <li><strong>Unfinished tasks:</strong> {{ unfinished_task }}</li>
      <br>
        <li><strong>Number of workers who are engaged in solving problems:</strong> {{ num_workers }}</li>
    </ul>

{% endblock %}

templates/task_manager/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete position?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-primary" href="javascript:history.back()">Cancel</a>
  </form>
{% endblock %}

templates/task_manager/position_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1><em>{{ object|yesno:"Update,Create" }} position</em></h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/position_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Position List
    <a href="{% url 'task_manager:position-create' %}" class="btn btn-primary link-to-page">
      Add new position
    </a>
  </h1>
  {% block search_form %}
    {% include "includes/search_form.html" %}
  {% endblock %}
  <br>
  {% if position_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for position in position_list %}
        <tr>
          <td>
              {{ position.id }}
          </td>
          <td>
              {{ position.name }}
          </td>
          <td>
              <a href="{% url 'task_manager:position-update' pk=position.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'task_manager:position-delete' pk=position.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no positions in the manager.</p>
  {% endif %}
{% endblock %}

templates/task_manager/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ task.name }}
    <a href="{% url 'task_manager:task-delete' pk=task.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'task_manager:task-update' pk=task.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <p>Description: {{ task.description }}</p>
  <p>Deadline: {{ task.deadline }}</p>
  <p>Is completed: {{ task.is_completed }}</p>
  <p>Priority: {{ task.priority }}</p>
  <p>Task type: {{ task.task_type }}</p>

  <h2>
    Assignees:

    {% if task in user.tasks.all %}
      <a href="{% url 'task_manager:toggle-task-assign' pk=task.id %}" class="btn btn-danger link-to-page">
        Delete me from this task
      </a>
    {% else %}
      <a href="{% url 'task_manager:toggle-task-assign' pk=task.id %}" class="btn btn-success link-to-page">
        Assign me to this task
      </a>
    {% endif %}

  </h2>
  <hr>
  <ul>
    {% for worker in task.assignees.all %}
      <li>
        <a href="{{ worker.get_absolute_url }}">{{ worker.username }}</a>
        ({{ worker.first_name }} {{ worker.last_name }})
      </li>
    {% empty %}
      <p>No assignees.</p>
    {% endfor %}
  </ul>
{% endblock %}

templates/task_manager/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1><em>{{ object|yesno:"Update,Create" }} task</em></h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Task list
    <a href="{% url 'task_manager:task-create' %}" class="btn btn-primary link-to-page">
      Create task
    </a>
    <a href="{% url 'task_manager:task-type-list' %}" class="btn btn-info link-to-page">
      Show all task types
    </a>
  </h1>
  <br>
    {% block search_form %}
      {% include "includes/search_form.html" %}
    {% endblock %}
  <br>
  {% if task_list %}
    <b>Completed task</b>
    <ul class="completed-task">
      {% for task in task_list %}
        {% if task.is_completed %}
          <li>
            <a href="{% url "task_manager:task-detail" pk=task.id %}">{{ task.name }}</a>
            ({{ task.description }})
          </li>
        {% endif %}
      {% endfor %}
    </ul>
    <b>Task in progress</b>
    <ul class="unfinished-task">
      {% for task in task_list %}
        {% if not task.is_completed %}
          <li>
            <a href="{% url "task_manager:task-detail" pk=task.id %} ">{{ task.name }}</a>
            ({{ task.description }})
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no task in manager.</p>
  {% endif %}
{% endblock %}

templates/task_manager/task_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task type?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-primary" href="javascript:history.back()">Cancel</a>
  </form>
{% endblock %}

templates/task_manager/task_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/task_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Task type List
    <a href="{% url 'task_manager:task-type-create' %}" class="btn btn-primary link-to-page">
      Add task type
    </a>
  </h1>
  <br>
  {% block search_form %}
    {% include "includes/search_form.html" %}
  {% endblock %}
  <br>
  {% if task_type_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for type in task_type_list %}
        <tr>
          <td>
              {{ type.id }}
          </td>
          <td>
              {{ type.name }}
          </td>
          <td>
              <a href="{% url 'task_manager:task-type-update' pk=type.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'task_manager:task-type-delete' pk=type.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no task types in the manager.</p>
  {% endif %}
{% endblock %}

templates/task_manager/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>DELETE worker?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-primary" href="javascript:history.back()">Cancel</a>
  </form>
{% endblock %}

templates/task_manager/worker_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
      Username: {{ worker.username }}
    {% if user.is_superuser %}
      <a href="{% url 'task_manager:worker-delete' pk=worker.id %}" class="btn btn-danger link-to-page">
        Delete
      </a>
    {% endif %}
  </h1>

  <p><strong>First name:</strong> {{ worker.first_name }}</p>
  <p><strong>Last name:</strong> {{ worker.last_name }}</p>
  <p><strong>Position:</strong> {{ worker.position }}</p>
  <p><strong>Is staff:</strong> {{ worker.is_staff }}</p>

  <div class="ml-3">
    <h4>Tasks</h4>

    {% for task in worker.tasks.all %}
      <hr>
      <div {% if task.is_completed %}
        class="completed-task"
        {% else %}
        class="unfinished-task"
      {% endif %}>

        <p><strong>Name:</strong> <a href="{% url "task_manager:task-detail" pk=task.id %}">{{ task.name }}</a></p>
        <p><strong>Task type:</strong> {{ task.task_type.name }}</p>
        <p><strong>Deadline:</strong> {{ task.deadline }}</p>
      </div>
    {% empty %}
      <p>No tasks.</p>
    {% endfor %}
  </div>
{% endblock %}

templates/task_manager/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1><em>Create worker</em></h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/worker_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>
      Worker List
      <a href="{% url 'task_manager:worker-create' %}" class="btn btn-primary link-to-page">
        Add an employee to the team
      </a>
      <a href="{% url 'task_manager:position-list' %}" class="btn btn-info link-to-page">
        Show all worker position
      </a>
    </h1>
    <br>
    {% block search_form %}
      {% include "includes/search_form.html" %}
    {% endblock %}
    <br>
    {% if worker_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Position</th>
      </tr>
    {% for worker in worker_list %}
      <tr>
        <td>{{ worker.id }}</td>
        <td><a href="{{ worker.get_absolute_url }}">{{ worker.username }} {% if user == worker %} (Me){% endif %}</a></td>
        <td>{{ worker.first_name }}</td>
        <td>{{ worker.last_name }}</td>
        <td>{{ worker.position }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no workers in the manager.</p>
    {% endif %}
{% endblock %}